"""
Stores the states accessed by the agents 
throughout the workflow
"""
from dotenv import load_dotenv
from typing import Annotated, Optional,TypedDict
import operator
from langchain_core.messages import MessageLikeRepresentation
from langgraph.graph import MessagesState
from pydantic import BaseModel, Field


def custom_reducer(value, new_value):
  """
  reducer which can either add or overwrite the messages
  """
  if isinstance(new_value, dict) and new_value.get("type") == "override":
    return new_value.get("value", new_value)
  else:
    return operator.add(value, new_value)

class AgentState(MessagesState):
  """
  State Main agent that contains the
  research topic and direction of research
  """
  # Messages exchanged between the supervisor and sub agents
  supervisor_messages : Annotated[list[MessageLikeRepresentation], custom_reducer]
  # Research brief generated by the agent
  research_brief : Optional[str]
  # raw data exchanged beteen the subagent and research agent
  raw_notes : Annotated[list[MessageLikeRepresentation], custom_reducer]
  # processed and formattted data
  notes : Annotated[list[MessageLikeRepresentation], custom_reducer]
  # final report generated by research
  final_report : str

class SupervisorState(TypedDict):
  """
  State for the supervisor state
  that manages the sub agents
  """
  # Messages exchanged between the supervisor and sub agents
  supervisor_messages : Annotated[list[MessageLikeRepresentation], custom_reducer]
  # Research brief generated by the agent
  research_brief : str
  # maxnimum number of agents to be spawned
  research_iterations : int
  # raw data exchanged beteen the subagent and research agent
  raw_notes : Annotated[list[MessageLikeRepresentation], custom_reducer]
  # processed and formattted data
  notes : Annotated[list[MessageLikeRepresentation], custom_reducer]

class ResearchState(TypedDict):
  """
  The agent that uses tools and 
  performs the websearch
  """
  # messages exchanged by the research agent and tools
  research_messages : Annotated[list[MessageLikeRepresentation], custom_reducer]
  # raw data exchanged beteen the subagent and research agent
  raw_notes : Annotated[list[MessageLikeRepresentation], custom_reducer]
  # summarized research
  compressed_reasearch : str
  # max number of tool calls:
  tool_call_iterations : int
  # topic of research
  research_topic : str 

### Structured outputs 
class UserQueryState(BaseModel):
  """
  state to get clarity if agents needs
  to more questions or ready to delve
  into research
  """
  need_clarification : bool = Field(description = "a boolean value that specifies if we need more questions from user")
  question : Optional[str] = Field(description = "Questions posed to the user to clarify", default = None)
  verification : Optional[str] = Field(description = "Verification messages if ready to proceed with research", default = None)

class ResearchBriefState(BaseModel):
  """
  state for the agent to understand the user needs
  and generate a research brief to guide the
  direction of the research
  """
  # Research brief generated by the agent
  research_brief : str = Field(description= "The research brief generated by the agent to direct research", default=None)

class ConductResearch(BaseModel):
  """
  calls the tool to conduct research on a certain topic
  """
  research_topic : str = Field(description="" \
  "The topic to research. Should be a single topic, and should be described in high detail (at least a paragraph)"
  )

class ResearchComplete(BaseModel):
    """Call this tool to indicate that the research is complete."""

class Summary(BaseModel):
  """
  Output state for the agent to generate the summary
  """
  summary : str = Field(description = "Summary of the webpage content")
  key_excerpts : str = Field(description = "Key excerpts from the webpage content")

class ResearcherOutputState(TypedDict):
  """
  state for the report writer agent
  """
  # raw data exchanged beteen the subagent and research agent
  raw_notes : Annotated[list[MessageLikeRepresentation], custom_reducer]
  # final report
  final_repot : str


